name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Authenticate
      run: dotnet nuget add source --username ${{github.REPOSITORY_OWNER}} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{github.REPOSITORY_OWNER}}/index.json"
    - name: Publish
      run: dotnet nuget push **/*.nupkg --source "github" --skip-duplicate
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-nupkg
        path: ./src/**/*.nupkg
        if-no-files-found: error
        retention-days: 0
